/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package grpc.jdbi.example;

import grpc.jdbi.example.jdbi.HikariDataSourceStrategy;
import grpc.jdbi.example.jdbi.JdbiClient;
import grpc.jdbi.example.jdbi.JdbiDataSource;
import grpc.jdbi.example.stub.Apple;
import grpc.jdbi.example.stub.Basket;
import grpc.jdbi.example.stub.Orange;
import grpc.jdbi.example.toolset.SimpleServiceClient;
import io.grpc.Server;
import io.grpc.ServerBuilder;
import io.grpc.StatusRuntimeException;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;

import java.io.IOException;
import java.util.List;


class SimpleServiceTest {

    private final static int PORT = 8080;
    private static PostgreSQLContainer postgreSQLContainer;
    private static Server app;

    @BeforeAll
    static void beforeAll() throws IOException {
        postgreSQLContainer = new PostgreSQLContainer("postgres:15.3")
                .withDatabaseName("test")
                .withUsername("user")
                .withPassword("topsecret");

        postgreSQLContainer.setPortBindings(List.of("5432:5432")); //TODO allow random ports

        postgreSQLContainer
                .withInitScript("init.sql")
                .withExposedPorts(5432);

        postgreSQLContainer.start();

        app = ServerBuilder.forPort(PORT)
                .addService(new SimpleService(defaultJdbiClient()))
                .build();

        app.start();
    }

    @AfterAll
    static void afterAll(){
        postgreSQLContainer.stop();
        app.shutdownNow();
    }

    @Test
    public void singleTableTest() {
        SimpleServiceClient simpleCli = new SimpleServiceClient(PORT);
        String id = simpleCli.addOrange(Orange.newBuilder().setColor("orange").setWeight(50).build());
        int amountOrange = simpleCli.getAllOranges().size();
        Assertions.assertNotNull(id);
        Assertions.assertTrue(amountOrange == 1);
    }

    @Test
    public void transactionTest() {
        SimpleServiceClient simpleCli = new SimpleServiceClient(PORT);
        Orange orange = Orange.newBuilder().setColor("orange").setWeight(500).build();
        Apple apple = Apple.newBuilder().setColor("green").setWeight(40).build();
        Assertions.assertThrows(StatusRuntimeException.class, () -> simpleCli.addBasket(Basket.newBuilder().setApple(apple).setOrange(orange).build()));
        int amountOrange = simpleCli.getAllOranges().stream().filter(o -> o.getWeight() == 500).toList().size();
        Assertions.assertTrue(amountOrange == 0);
    }

    @Test
    public void transactionServiceTest() {
        SimpleServiceClient simpleCli = new SimpleServiceClient(PORT);
        Orange orange = Orange.newBuilder().setColor("orange").setWeight(505).build();
        Apple apple = Apple.newBuilder().setColor("green").setWeight(40).build();
        Assertions.assertThrows(StatusRuntimeException.class, () -> simpleCli.addBasketManually(Basket.newBuilder().setApple(apple).setOrange(orange).build()));
        int amountOrange = simpleCli.getAllOranges().stream().filter(o -> o.getWeight() == 505).toList().size();
        Assertions.assertTrue(amountOrange == 0);
    }

    private static JdbiClient defaultJdbiClient() {
        JdbiDataSource dataSourceStrategy = new HikariDataSourceStrategy();
        return JdbiClient.getInstance(dataSourceStrategy);
    }
}
